### ISSUE TITLE
Resolve input files relative to an input directory

### ISSUE THREAD

**Issue by drmalex07** [OpertusMundi/profile#2]
When input is given as a reference to a file it must be resolved as a relative path against an input directory.
The input directory itself must be given as an environment variable `INPUT_DIR` of the service.

Now, the input file is assumed to accessible from both server and client on the same path. This is not practical (especially when server runs inside a container), because server and client do not necessarily  share the same view of the flesystem.

**Comment by kPsarakis** [comment]
Resolved in commit 989fbb0.

Problems that came up and were resolved:
Reading files with [geovaex](https://github.com/OpertusMundi/geovaex) generate an arrow file. By default, this is stored in the same folder as the input file. Now the `INPUT_DIR` is read-only thus we store the arrow files in their temp folder.
